# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  label_path: ./data/kinetics/val_label.pkl
  debug: False
  modf: noise
  drop_num: 1 # here
  ntype: Chaos
  ttype: Fix # here

# model
model: model.magcn.Model
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [0,1,2,3]
test_batch_size: 512


weights: ./runs/weights/ki_agcn_joint_mutual5dynamic_v2-main-64-123948.pt
ar_weights: ./runs/weights/ki_agcn_joint_mutual5dynamic_v2-regression-64-123948.pt

work_dir: ./work_dir/kinetics/pegcm_joint_test
model_saved_name: ./runs/ki_pegcn_joint_test
save_score: True
