ar_weights: ./runs/weights/ki_agcn_joint_mutual5dynamic_v2-regression-64-123948.pt
device:
- 0
- 1
- 2
- 3
feeder: feeders.feeder.Feeder
model: model.magcn.Model
model_args:
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 400
  num_person: 2
  num_point: 18
model_saved_name: ./runs/ki_pegcn_joint_test
phase: test
save_score: true
test_batch_size: 512
test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  debug: false
  drop_num: 10
  label_path: ./data/kinetics/val_label.pkl
  modf: noise
  ntype: Chaos
  ttype: Fix
weights: ./runs/weights/ki_agcn_joint_mutual5dynamic_v2-main-64-123948.pt
work_dir: ./work_dir/kinetics/pegcm_joint_test
