work_dir: ./work_dir/kinetics/pegcn_joint_v2
model_saved_name: ./runs/ki_agcn_joint_mutual5dynamic_v2
weights: ./runs/ki_agcn_joint_mutual5dynamic_v2-main-64-123948.pt
ar_weights: ./runs/ki_agcn_joint_mutual5dynamic_v2-regression-64-123948.pt
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ./data/kinetics/train_data_joint.npy
  label_path: ./data/kinetics/train_label.pkl
  debug: False
  modf: mutual
  drop_num: 5 # here
  ntype: Chaos
  ttype: dynamic # here

test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  label_path: ./data/kinetics/val_label.pkl
  modf: noise
  drop_num: 1 # here
  ntype: Chaos
  ttype: Fix # here

# model
model: model.magcn.Model
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [35, 55]

# training
device: [0, 1, 2, 3]
batch_size: 128
test_batch_size: 128
num_epoch: 100
nesterov: True




