
# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl
  debug: False
  modf: normal # here
  drop_num: 5 # here
  ntype: Chaos # here
  ttype: dynamic # here
# model
model: model.magcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0,1,2,3]
test_batch_size: 128
#device: [0]
#test_batch_size: 1
#test_batch_size: 128

save_score: True
modf: normal # here
work_dir: ./work_dir/ntu/xview/agcn_test_joint
model_saved_name: ./runs/ntu_cv_agcn_joint_mutual5dynamic-regression # here
weights: ./runs/ntu_cv_agcn_joint_mutual5dynamic-main-49-59976.pt # here
ar_weights: ./runs/ntu_cv_agcn_joint_mutual5dynamic-regression-49-59976.pt
