ar_weights: ./runs/weights/ntu_cv_joint_mutual5dynamic_ce-regression-39-49392.pt
device:
- 0
- 1
- 2
- 3
feeder: feeders.feeder.Feeder
model: model.magcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cv_agcn_joint_mutual5dynamic-regression
modf: mutual
phase: test
save_score: true
test_batch_size: 16
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  debug: false
  drop_num: 1
  label_path: ./data/ntu/xview/val_label.pkl
  modf: noise
  ntype: Choas
  ttype: Fix
weights: ./runs/weights/ntu_cv_joint_mutual5dynamic_ce-main-39-49392.pt
work_dir: ./work_dir/ntu_cv_joint_mutual5dynamic_ce
