work_dir: ./work_dir/ntu/xsub/magcn_test_joint
model_saved_name: ./runs/ntu_cs_agcn_joint_mutual5dynamic-regression # here
modf: mutual
weights: ./runs/weights/ntu_cs_agcn_joint_mutual5dynamic-main-49-62600.pt # here
ar_weights: ./runs/weights/ntu_cs_agcn_joint_mutual5dynamic-regression-49-62600.pt


# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint.npy
  label_path: ./data/ntu/xsub/val_label.pkl
  debug: False
  modf: normal # here
  drop_num: 5 # here
  ntype: Chaos # here
  ttype: fix # here

# model
model: model.magcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0,1,2,3]
test_batch_size: 256
save_score: True